### PR TITLE
Try to fix "No device was found" in MacOS

### PR DESCRIPTION
**Pull request by SwitchBot-Wonderlabs**
Getting address from manufacturer data.

Add Curtain pause command.

### CODE REVIEW

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @futomi , we are ready.

**Comment by futomi** [comment]
> Hey, @futomi , we are ready.

Though I tried to transfer the ownership to you, it was rejected because the node-switchbot already exists on your account. What should I do? Should I rename the repository name?

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs You will have to delete your fork then @futomi can transfer ownership

**Comment by donavanbecker** [comment]
> > Hey, @futomi , we are ready.
> 
> 
> 
> Though I tried to transfer the ownership to you, it was rejected because the node-switchbot already exists on your account. What should I do? Should I rename the repository name?

I would merge this then they can delete the fork and you can transfer again.

**Comment by SwitchBot-Wonderlabs** [comment]
@futomi You can transfer to `OpenWonderLabs` organization.

**Comment by futomi** [comment]
Hi, @SwitchBot-Wonderlabs.

> @futomi You can transfer to OpenWonderLabs organization.

I tried to transfer the repository to `OpenWonderLabs`. The error below was shown:

> You don’t have the permission to create public repositories on OpenWonderLabs

What should I do?

**Comment by donavanbecker** [comment]
@futomi If you transfer to me, I can transfer to the organization.

**Comment by SwitchBot-Wonderlabs** [comment]
> Hi, @SwitchBot-Wonderlabs.
> 
> > @futomi You can transfer to OpenWonderLabs organization.
> 
> I tried to transfer the repository to `OpenWonderLabs`. The error below was shown:
> 
> > You don’t have the permission to create public repositories on OpenWonderLabs
> 
> What should I do?

Hi, @futomi , you can transfer it to @donavanbecker, or join the OpenWonderLabs organization then transfer it to OpenWonderLabs.

**Comment by futomi** [comment]
Hi, @donavanbecker, @SwitchBot-Wonderlabs

Thank you for your advice. I transferred to `donavanbecker`. @donavanbecker, Could you check the request?
I have to transfer the npm repository to you as well. Could you tell me your npm account?

**Comment by donavanbecker** [comment]
donavanbecker is also my npm.
I got the GitHub transfer request.

**Comment by futomi** [comment]
@donavanbecker, I transferred the npm package to you. Could you check the invitation?

**Comment by donavanbecker** [comment]
@futomi good to go! Thanks!

**Pull request merged**
